save_data: ./example

# Corpus opts:
data:
    corpus:
        path_src: segmented/train_2.bpe.src
        path_tgt: segmented/train_2.bpe.tgt
    valid:
        path_src: segmented/val.bpe.src
        path_tgt: segmented/val.bpe.tgt


## Where the vocab(s) will be written
src_vocab: vocab/vocab.src
tgt_vocab: vocab/vocab.tgt

# General opts
save_model: model/transformer_2
train_steps: 500000
save_checkpoint_steps: 25000
valid_steps: 10000
early_stopping: 5
early_stopping_criteria: ppl

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout: 0.2
attention_dropout: 0.1



# Optimization
model_dtype: fp32
optim: adam
learning_rate: 2
warmup_steps: 8000
decay_method: noam
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: tokens

# Batching
world_size: 1
gpu_ranks: [0]
batch_type: tokens
batch_size: 4096
valid_batch_size: 4096
max_generator_batches: 2
accum_count: 8
